modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
authors="Axel vazquez" #optional

[[mods]] #mandatory
modId="blockbreakinfo" #mandatory
version="1.0.0" #mandatory
displayName="Block Break Info" #mandatory
description='''
Display block breaking info.
Info
-Can harvest block
-Time left to harvest
-Progress
'''

[[dependencies.blockbreakinfo]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.blockbreakinfo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"